#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Capability / load test suite for the event_loop pipeline mode.
#
# Runs the six sustained-stream capability checks against the no-GPU
# functional-test simulators: concurrency exceeding thread count with flat
# consumer lag below the knee (event_loop), the thread-bound contrast
# (thread_bridge), flat per-call VLM latency up to the cap, hard VLM/VST
# concurrency caps under overload, and bounded in-flight with zero message
# loss. Load is generated by incident_stream_publisher.py in --unique mode
# (survivor rate == injection rate); simulated VLM latency comes from the
# threaded NIM stub's NIM_STUB_DELAY_SECONDS.
#
# Usage: ./run_capability.sh [--test TS-001] [--skip-setup]
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FUNCTIONAL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
P1_ROOT="$FUNCTIONAL_ROOT/p1"
REPO_ROOT="$(cd "$FUNCTIONAL_ROOT/../.." && pwd)"
source "$P1_ROOT/shared/helpers.sh"

export PID_DIR="${PID_DIR:-/tmp/alert_agent_p1_functional}"
ES_HOST="${ES_HOST:-http://127.0.0.1:9200}"
BOOTSTRAP="${BOOTSTRAP:-127.0.0.1:9092}"
TOPIC="${TOPIC:-mdx-incidents}"
BASE_CONFIG="$P1_ROOT/shared/config_base.yaml"
CONSUMER_GROUP="alert-bridge-vlm-group-p1"
KAFKA_CONTAINER="alert-agent-kafka-test"
METRICS_URL="http://127.0.0.1:9081/metrics"
RESULTS_DIR="$PID_DIR/capability_results"
INJECTOR="$SCRIPT_DIR/incident_stream_publisher.py"

ONLY_TEST=""
SKIP_SETUP=0
while [ $# -gt 0 ]; do
    case "$1" in
        --test) ONLY_TEST="$2"; shift 2 ;;
        --skip-setup) SKIP_SETUP=1; shift ;;
        *) echo "Unknown option: $1"; exit 2 ;;
    esac
done

mkdir -p "$PID_DIR" "$RESULTS_DIR"

PASS_COUNT=0
FAIL_COUNT=0
declare -a RESULTS=()

record_result() {
    local name="$1" status="$2" detail="$3"
    RESULTS+=("$status  $name  $detail")
    if [ "$status" = "PASS" ]; then PASS_COUNT=$((PASS_COUNT+1)); else FAIL_COUNT=$((FAIL_COUNT+1)); fi
    print_status "$([ "$status" = "PASS" ] && echo ok || echo fail)" "$name: $status — $detail"
}

# ─── Stack management ────────────────────────────────────────────────────────

ensure_stack() {
    if ! nc -z 127.0.0.1 9092 2>/dev/null; then
        print_status "wait" "Starting Kafka container..."
        docker rm -f "$KAFKA_CONTAINER" 2>/dev/null || true
        docker run -d --name "$KAFKA_CONTAINER" -p 9092:9092 \
            -e KAFKA_BROKER_ID=1 -e KAFKA_PROCESS_ROLES=broker,controller -e KAFKA_NODE_ID=1 \
            -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
            -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
            -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 \
            -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 \
            -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
            -e KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
            -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
            -e CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk \
            confluentinc/cp-kafka:7.5.0 >/dev/null
        local waited=0
        while [ $waited -lt 60 ] && ! nc -z 127.0.0.1 9092 2>/dev/null; do sleep 1; waited=$((waited+1)); done
        sleep 5
    fi
    for topic in mdx-incidents mdx-alerts; do
        docker exec "$KAFKA_CONTAINER" kafka-topics --create --bootstrap-server localhost:9092 \
            --topic "$topic" --partitions 1 --replication-factor 1 2>/dev/null || true
    done

    if ! curl -sf http://127.0.0.1:9200/health >/dev/null 2>&1; then
        python3 "$REPO_ROOT/test/sim_scripts/elastic/elastic_sim.py" > "$PID_DIR/elastic_sim.log" 2>&1 &
        echo $! > "$PID_DIR/elastic_sim.pid"
    fi
    if ! curl -sf http://127.0.0.1:30888/status >/dev/null 2>&1; then
        python3 "$REPO_ROOT/test/sim_scripts/vst/vst_sim.py" > "$PID_DIR/vst_sim.log" 2>&1 &
        echo $! > "$PID_DIR/vst_sim.pid"
    fi
    if ! curl -sf http://127.0.0.1:8080/models >/dev/null 2>&1; then
        python3 "$REPO_ROOT/test/sim_scripts/vss/vss_sim.py" > "$PID_DIR/vss_sim.log" 2>&1 &
        echo $! > "$PID_DIR/vss_sim.pid"
    fi
    sleep 2
    start_nim_stub 0
}

start_nim_stub() {
    local delay="$1"
    if [ -f "$PID_DIR/nim_sim.pid" ]; then
        local pid; pid=$(cat "$PID_DIR/nim_sim.pid")
        kill "$pid" 2>/dev/null || true
        sleep 1
        kill -9 "$pid" 2>/dev/null || true
    fi
    NIM_STUB_DELAY_SECONDS="$delay" \
        python3 "$REPO_ROOT/test/sim_scripts/nim/nim_stub_server.py" > "$PID_DIR/nim_sim.log" 2>&1 &
    echo $! > "$PID_DIR/nim_sim.pid"
    sleep 2
}

restart_vst_sim() {
    local delay="$1"
    if [ -f "$PID_DIR/vst_sim.pid" ]; then
        local pid; pid=$(cat "$PID_DIR/vst_sim.pid")
        kill "$pid" 2>/dev/null || true
        sleep 1
        kill -9 "$pid" 2>/dev/null || true
    fi
    VST_SIM_DELAY_SECONDS="$delay" \
        python3 "$REPO_ROOT/test/sim_scripts/vst/vst_sim.py" > "$PID_DIR/vst_sim.log" 2>&1 &
    echo $! > "$PID_DIR/vst_sim.pid"
    sleep 2
}

# ─── Alert Bridge lifecycle (Prometheus enabled) ─────────────────────────────

build_config() {
    # build_config OUT MODE NUM_WORKERS ADW MAX_IN_FLIGHT VLM_CAP VST_CAP [MAX_POLL]
    python3 - "$BASE_CONFIG" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "${8:-50}" <<'PY'
import sys, yaml
src, dst, mode, nw, adw, mif, vlm_cap, vst_cap, max_poll = sys.argv[1:10]
with open(src) as f:
    cfg = yaml.safe_load(f)
aa = cfg.setdefault('alert_agent', {})
aa['pipeline_mode'] = mode
aa['num_workers'] = int(nw)
aa['async_dispatch_workers'] = int(adw)
aa['async_dispatch_max_in_flight'] = int(mif)
aa['include_latency_info'] = True
aio = aa.setdefault('async_io', {})
aio['max_vlm_concurrent'] = int(vlm_cap)
aio['max_vst_concurrent'] = int(vst_cap)
# Sustained-stream ingest must not be poll-starved (empty second topic).
k = cfg.setdefault('kafka', {})
k['poll_timeout'] = 50
k['max_poll_records'] = int(max_poll)
vlm = cfg.setdefault('vlm', {})
vlm['request_timeout'] = 120
with open(dst, 'w') as f:
    yaml.safe_dump(cfg, f, sort_keys=False)
PY
}

stop_ab() {
    stop_alert_bridge_local "$PID_DIR"
    local waited=0
    while [ $waited -lt 10 ] && { nc -z 127.0.0.1 9080 2>/dev/null || nc -z 127.0.0.1 9081 2>/dev/null; }; do
        sleep 1; waited=$((waited+1))
    done
}

start_ab() {
    local config="$1"
    local config_dir; config_dir="$(cd "$(dirname "$config")" && pwd)"
    ALERT_AGENT_CONFIG_DIR="$config_dir" PROMETHEUS_METRICS_ENABLED=true \
        python3 "$REPO_ROOT/enhance_alert_with_vlm.py" --config "$config" > "$PID_DIR/alert_bridge.log" 2>&1 &
    echo $! > "$PID_DIR/alert_bridge.pid"
    local waited=0
    while [ $waited -lt 90 ]; do
        # Readiness now trails the consumer group join, so no settle needed.
        if grep -q "Starting anomaly processing loop" "$PID_DIR/alert_bridge.log" 2>/dev/null; then
            return 0
        fi
        if ! kill -0 "$(cat "$PID_DIR/alert_bridge.pid")" 2>/dev/null; then
            print_status "fail" "Alert Bridge exited during startup"
            tail -5 "$PID_DIR/alert_bridge.log" || true
            return 1
        fi
        sleep 1; waited=$((waited+1))
    done
    print_status "fail" "Alert Bridge did not reach processing loop"
    return 1
}

# ─── Signal helpers ──────────────────────────────────────────────────────────

prom_value() {
    curl -s "$METRICS_URL" 2>/dev/null | awk -v m="$1" '$1==m {v=$2} END{if(v=="")v=0; print v}'
}

group_lag() {
    kafka_consumer_lag "$CONSUMER_GROUP"
}

run_injector() {
    # run_injector RATE DURATION PREFIX [SENSORS]
    python3 "$INJECTOR" --bootstrap "$BOOTSTRAP" --topic "$TOPIC" \
        --num-sensors "${4:-4}" --rate "$1" --duration "$2" \
        --unique --sensor-prefix "$3" > "$RESULTS_DIR/injector_$3.log" 2>&1
}

sample_loop() {
    # sample_loop SECONDS INTERVAL OUTFILE  — rows: epoch,stub_inflight,stub_peak,lag,el_vlm,el_vst,dispatch
    local seconds="$1" interval="$2" out="$3"
    local end=$(( $(date +%s) + seconds ))
    while [ "$(date +%s)" -lt "$end" ]; do
        local stats; stats=$(nim_stub_stats)
        local inflight peak
        inflight=$(echo "$stats" | python3 -c "import sys,json;print(json.load(sys.stdin).get('in_flight',0))" 2>/dev/null || echo 0)
        peak=$(echo "$stats" | python3 -c "import sys,json;print(json.load(sys.stdin).get('peak_in_flight',0))" 2>/dev/null || echo 0)
        echo "$(date +%s),$inflight,$peak,$(group_lag),$(prom_value alert_bridge_event_loop_vlm_in_flight),$(prom_value alert_bridge_event_loop_vst_in_flight),$(prom_value alert_bridge_dispatch_in_flight)" >> "$out"
        sleep "$interval"
    done
}

analyze_samples() {
    # analyze_samples FILE FIELD  → prints "max first_third_avg last_third_avg all_leq(cap)? given CAP via env"
    python3 - "$1" "$2" <<'PY'
import sys
path, field = sys.argv[1], int(sys.argv[2])
rows = []
with open(path) as f:
    for line in f:
        parts = line.strip().split(',')
        if len(parts) > field:
            try:
                rows.append(float(parts[field]))
            except ValueError:
                pass
if not rows:
    print("0 0 0")
    sys.exit(0)
third = max(1, len(rows)//3)
first = sum(rows[:third])/third
last = sum(rows[-third:])/third
print(f"{max(rows):.1f} {first:.1f} {last:.1f}")
PY
}

reset_es() {
    local today; today=$(date -u +%Y-%m-%d)
    curl -sf -X DELETE "$ES_HOST/mdx-vlm-incidents-$today" >/dev/null 2>&1 || true
    curl -sf -X DELETE "$ES_HOST/ab-confirmed-verdicts" >/dev/null 2>&1 || true
}

prepare_run() {
    # prepare_run MODE NW ADW MIF VLM_CAP VST_CAP NIM_DELAY [MAX_POLL]
    local cfg="$PID_DIR/capability_config.yaml"
    stop_ab
    # Committed offsets persist across AB restarts: skip any leftover backlog
    # from a previous (overload) test so each test starts at lag 0.
    docker exec "$KAFKA_CONTAINER" kafka-consumer-groups --bootstrap-server localhost:9092 \
        --group "$CONSUMER_GROUP" --reset-offsets --to-latest --all-topics --execute >/dev/null 2>&1 || true
    start_nim_stub "$7"
    reset_es
    build_config "$cfg" "$1" "$2" "$3" "$4" "$5" "$6" "${8:-50}"
    start_ab "$cfg" || return 1
    # Let the startup VLM warmup request drain before zeroing stub counters,
    # so it cannot leak into the measured concurrency window.
    local waited=0
    while [ $waited -lt 20 ]; do
        local infl; infl=$(nim_stub_stat in_flight)
        [ "${infl:-1}" = "0" ] && break
        sleep 1; waited=$((waited+1))
    done
    nim_stub_reset
    local mode_line
    mode_line=$(grep "Pipeline mode is" "$PID_DIR/alert_bridge.log" | tail -1)
    print_status "info" "AB up — ${mode_line##* is }"
}

# ─── TS-001: event_loop concurrency exceeds thread count; lag flat ──────────
ts_001() {
    echo ""; echo "=== TS-001: concurrency > thread count, lag flat below knee (event_loop) ==="
    prepare_run event_loop 2 2 40 20 20 3 || { record_result TS-001 FAIL "AB startup"; return; }
    local samples="$RESULTS_DIR/ts001_samples.csv"; : > "$samples"
    run_injector 5 150 TS001 &
    local inj=$!
    sample_loop 160 5 "$samples"
    wait $inj || true

    read -r lmax lfirst llast <<< "$(analyze_samples "$samples" 3)"
    read -r gmax _ _ <<< "$(analyze_samples "$samples" 4)"
    local peak; peak=$(nim_stub_stat peak_in_flight)

    # Pipeline-scoped concurrency comes from the AB gauge; the stub peak also
    # counts non-message requests (startup warmup) and is informational.
    local detail="gauge_max=$gmax (workers=2, cap=20) stub_peak=$peak lag first/last=$lfirst/$llast"
    if python3 -c "
import sys
gauge_max, lfirst, llast = float('$gmax'), float('$lfirst'), float('$llast')
sys.exit(0 if (gauge_max > 2 and gauge_max <= 20 and llast <= lfirst + 10) else 1)"; then
        record_result TS-001 PASS "$detail"
    else
        record_result TS-001 FAIL "$detail"
    fi
}

# ─── TS-002: thread_bridge contrast — capped at thread count, lag grows ─────
ts_002() {
    echo ""; echo "=== TS-002: thread_bridge thread-bound ceiling (contrast) ==="
    prepare_run thread_bridge 2 2 4 20 20 3 || { record_result TS-002 FAIL "AB startup"; return; }
    local samples="$RESULTS_DIR/ts002_samples.csv"; : > "$samples"
    run_injector 5 150 TS002 &
    local inj=$!
    sample_loop 160 5 "$samples"
    wait $inj || true

    read -r lmax lfirst llast <<< "$(analyze_samples "$samples" 3)"
    local peak; peak=$(nim_stub_stat peak_in_flight)

    local detail="vlm_peak=$peak (adw=2) lag first/last=$lfirst/$llast max=$lmax"
    if [ "$peak" -le 2 ] \
       && python3 -c "import sys; sys.exit(0 if float('$llast') > float('$lfirst') + 50 else 1)"; then
        record_result TS-002 PASS "$detail"
    else
        record_result TS-002 FAIL "$detail"
    fi
}

# ─── TS-003: effective vlm_duration flat as concurrency ramps to cap ────────
ts_003() {
    echo ""; echo "=== TS-003: vlm_duration flat across concurrency ramp (event_loop) ==="
    prepare_run event_loop 2 2 40 10 20 2 || { record_result TS-003 FAIL "AB startup"; return; }
    local means=()
    for rate in 1 3 5; do
        local s0 c0 s1 c1
        s0=$(prom_value alert_bridge_vlm_duration_seconds_sum)
        c0=$(prom_value alert_bridge_vlm_duration_seconds_count)
        run_injector "$rate" 60 "TS003R$rate"
        sleep 8   # let in-flight calls finish observing
        s1=$(prom_value alert_bridge_vlm_duration_seconds_sum)
        c1=$(prom_value alert_bridge_vlm_duration_seconds_count)
        means+=("$(python3 -c "s=$s1-$s0;c=$c1-$c0;print(f'{s/c:.3f}' if c>0 else '0')")")
    done
    local base="${means[0]}"
    local detail="mean@1/s=${means[0]} @3/s=${means[1]} @5/s=${means[2]} (stub=2s)"
    if python3 -c "
import sys
base, m2, m3 = float('${means[0]}'), float('${means[1]}'), float('${means[2]}')
ok = base > 0 and m2 <= base*1.2 and m3 <= base*1.2
sys.exit(0 if ok else 1)"; then
        record_result TS-003 PASS "$detail"
    else
        record_result TS-003 FAIL "$detail"
    fi
}

# ─── TS-004: VLM cap never exceeded under overload ───────────────────────────
ts_004() {
    echo ""; echo "=== TS-004: VLM cap never exceeded under overload (event_loop) ==="
    prepare_run event_loop 2 2 40 5 20 3 || { record_result TS-004 FAIL "AB startup"; return; }
    local samples="$RESULTS_DIR/ts004_samples.csv"; : > "$samples"
    run_injector 10 180 TS004 &
    local inj=$!
    sample_loop 190 1 "$samples"
    wait $inj || true

    # Zero-tolerance check on the pipeline gauge (EVENT_LOOP_VLM_IN_FLIGHT per
    # spec); the stub count also sees transport-level artifacts (SDK retries,
    # startup warmup) and is diagnostic only.
    local violations gauge_max
    read -r violations gauge_max <<< "$(python3 - "$samples" <<'PY'
import sys
count = 0
gmax = 0.0
with open(sys.argv[1]) as f:
    for line in f:
        parts = line.strip().split(',')
        if len(parts) > 4:
            try:
                v = float(parts[4])
            except ValueError:
                continue
            gmax = max(gmax, v)
            if v > 5:
                count += 1
print(count, gmax)
PY
)"
    local peak; peak=$(nim_stub_stat peak_in_flight)
    local detail="gauge_max=$gauge_max cap=5 gauge_samples_over_cap=$violations stub_peak=$peak"
    if python3 -c "import sys; sys.exit(0 if int('$violations')==0 and float('$gauge_max')==5.0 else 1)"; then
        record_result TS-004 PASS "$detail"
    else
        record_result TS-004 FAIL "$detail"
    fi
}

# ─── TS-005: VST cap never exceeded (delayed VST sim) ────────────────────────
ts_005() {
    echo ""; echo "=== TS-005: VST cap never exceeded (event_loop, delayed VST) ==="
    restart_vst_sim 1.5
    prepare_run event_loop 2 2 40 20 4 0 || { record_result TS-005 FAIL "AB startup"; restart_vst_sim 0; return; }
    local samples="$RESULTS_DIR/ts005_samples.csv"; : > "$samples"
    run_injector 8 90 TS005 &
    local inj=$!
    sample_loop 100 1 "$samples"
    wait $inj || true
    restart_vst_sim 0

    read -r vstmax _ _ <<< "$(analyze_samples "$samples" 5)"
    local detail="event_loop_vst_in_flight max=$vstmax cap=4"
    if python3 -c "import sys; m=float('$vstmax'); sys.exit(0 if 2 <= m <= 4 else 1)"; then
        record_result TS-005 PASS "$detail"
    else
        record_result TS-005 FAIL "$detail"
    fi
}

# ─── TS-006: bounded in-flight + zero loss under sustained overload ─────────
ts_006() {
    echo ""; echo "=== TS-006: bounded in-flight, zero loss under overload (event_loop) ==="
    prepare_run event_loop 2 2 20 5 20 3 || { record_result TS-006 FAIL "AB startup"; return; }
    local samples="$RESULTS_DIR/ts006_samples.csv"; : > "$samples"
    run_injector 3 300 TS006 20 &
    local inj=$!
    sample_loop 310 2 "$samples"
    wait $inj || true
    local produced
    produced=$(grep -o "DONE sent=[0-9]*" "$RESULTS_DIR/injector_TS006.log" | grep -o "[0-9]*")

    # Drain: knee = 5/3s ≈ 1.67/s; backlog ≈ (3-1.67)*300 ≈ 400 → ~4-5 min
    print_status "wait" "Draining backlog (produced=$produced)..."
    local waited=0
    while [ $waited -lt 420 ]; do
        local lag; lag=$(group_lag)
        local infl; infl=$(prom_value alert_bridge_dispatch_in_flight)
        if [ "${lag:-1}" -eq 0 ] 2>/dev/null && python3 -c "import sys; sys.exit(0 if float('$infl')==0 else 1)"; then
            break
        fi
        sleep 10; waited=$((waited+10))
    done

    read -r dmax _ _ <<< "$(analyze_samples "$samples" 6)"
    local events_total after_dedup
    events_total=$(curl -s "$METRICS_URL" | awk '/^alert_bridge_events_total\{/ {sum += $2} END {print sum+0}')
    after_dedup=$(prom_value alert_bridge_events_after_dedup_total)
    local docs; docs=$(count_es_docs "$ES_HOST")

    local detail="produced=$produced after_dedup=$after_dedup events_total=$events_total es_docs=$docs dispatch_in_flight_max=$dmax (cap=20)"
    if python3 -c "
import sys
produced, after_dedup, events_total, docs, dmax = $produced, $after_dedup, $events_total, $docs, float('$dmax')
ok = (dmax <= 20
      and after_dedup == produced
      and events_total == after_dedup
      and docs == events_total)
sys.exit(0 if ok else 1)"; then
        record_result TS-006 PASS "$detail"
    else
        record_result TS-006 FAIL "$detail"
    fi
}

# ─── TS-011: restart sweep across all modes, clean behavior each time ───────
ts_011() {
    echo ""; echo "=== TS-011: restart sweep sync→thread_bridge→event_loop→thread_bridge→sync ==="
    local step=0 failed=0 detail=""
    for mode in sync thread_bridge event_loop thread_bridge sync; do
        step=$((step+1))
        prepare_run "$mode" 2 2 8 8 8 0 || { failed=1; detail="step$step($mode): startup"; break; }

        local expected_line=""
        case "$mode" in
            sync)          expected_line="Pipeline mode is sync" ;;
            thread_bridge) expected_line="Async message dispatch enabled" ;;
            event_loop)    expected_line="Event-loop message dispatch enabled" ;;
        esac
        if ! grep -q "$expected_line" "$PID_DIR/alert_bridge.log"; then
            failed=1; detail="step$step($mode): missing '$expected_line'"; break
        fi

        local prefix="TS011S${step}"
        python3 "$INJECTOR" --bootstrap "$BOOTSTRAP" --topic "$TOPIC" \
            --identical-burst 1 --sensor-prefix "$prefix" >> "$RESULTS_DIR/injector_TS011.log" 2>&1
        if ! poll_es_doc_by_sensor "$ES_HOST" "${prefix}_001" 60 3 >/dev/null; then
            failed=1; detail="step$step($mode): no ES doc for ${prefix}_001"; break
        fi
        if grep -q "Traceback (most recent call last)" "$PID_DIR/alert_bridge.log"; then
            failed=1; detail="step$step($mode): traceback in log"; break
        fi
    done
    if [ "$failed" -eq 0 ]; then
        record_result TS-011 PASS "5 restarts, each mode processed E2E with clean logs"
    else
        record_result TS-011 FAIL "$detail"
    fi
}

# ─── TS-014: offset commit at consume time; kill mid-flight → no reprocess ──
ts_014() {
    echo ""; echo "=== TS-014: at-most-once — kill mid-flight, not reprocessed on restart ==="
    prepare_run event_loop 2 2 8 8 8 15 || { record_result TS-014 FAIL "AB startup"; return; }

    python3 "$INJECTOR" --bootstrap "$BOOTSTRAP" --topic "$TOPIC" \
        --identical-burst 1 --sensor-prefix TS014 > "$RESULTS_DIR/injector_TS014.log" 2>&1

    if ! nim_stub_wait_in_flight 1 30; then
        record_result TS-014 FAIL "message never reached VLM"
        return
    fi
    # Consumed + offset committed + VLM call held by the 15s stub → hard-kill
    local lag_mid; lag_mid=$(group_lag)
    kill -9 "$(cat "$PID_DIR/alert_bridge.pid")" 2>/dev/null || true
    pkill -9 -f "enhance_alert_with_vlm.py" 2>/dev/null || true
    sleep 2
    nim_stub_reset

    # Restart with the SAME consumer group; a committed offset must not replay
    local cfg="$PID_DIR/capability_config.yaml"
    start_nim_stub 15
    start_ab "$cfg" || { record_result TS-014 FAIL "AB restart"; return; }
    nim_stub_reset
    sleep 20

    local replays lag_end docs
    replays=$(nim_stub_stat total_requests)
    lag_end=$(group_lag)
    docs=$(get_all_es_docs "$ES_HOST" | SENSOR_ID="TS014_001" python3 -c "
import json, os, sys
sensor = os.environ['SENSOR_ID']
docs = json.load(sys.stdin)
print(sum(1 for d in docs if str(d.get('sensorId','')) == sensor))
" 2>/dev/null || echo 0)

    local detail="lag_mid_flight=$lag_mid vlm_requests_after_restart=$replays lag_after=$lag_end es_docs=$docs"
    if [ "$lag_mid" -eq 0 ] && [ "$replays" -eq 0 ] && [ "$lag_end" -eq 0 ] && [ "$docs" -eq 0 ]; then
        record_result TS-014 PASS "$detail (commit precedes completion; killed in-flight not reprocessed)"
    else
        record_result TS-014 FAIL "$detail"
    fi
}

# ─── TS-020: dedup check-and-set atomic under real concurrency ──────────────
ts_020() {
    echo ""; echo "=== TS-020: concurrent identical-fingerprint burst → exactly 1 survivor ==="
    # max_poll_records=1 spreads the burst across the 10-worker pool so the
    # dedup cache is hit from many threads at once.
    prepare_run event_loop 10 2 40 20 20 1 1 || { record_result TS-020 FAIL "AB startup"; return; }

    python3 "$INJECTOR" --bootstrap "$BOOTSTRAP" --topic "$TOPIC" \
        --identical-burst 20 --sensor-prefix TS020 > "$RESULTS_DIR/injector_TS020.log" 2>&1

    # Settle: 20 consumes + 1 VLM call (1s stub)
    local waited=0
    while [ $waited -lt 60 ]; do
        local lag; lag=$(group_lag)
        [ "${lag:-1}" -eq 0 ] 2>/dev/null && break
        sleep 2; waited=$((waited+2))
    done
    sleep 8

    local after_dedup dropped docs
    after_dedup=$(prom_value alert_bridge_events_after_dedup_total)
    dropped=$(curl -s "$METRICS_URL" | awk '/^alert_bridge_events_dropped_total\{/ {sum += $NF} END {print sum+0}')
    docs=$(get_all_es_docs "$ES_HOST" | SENSOR_ID="TS020_001" python3 -c "
import json, os, sys
sensor = os.environ['SENSOR_ID']
docs = json.load(sys.stdin)
print(sum(1 for d in docs if str(d.get('sensorId','')) == sensor))
" 2>/dev/null || echo 0)

    local detail="after_dedup=$after_dedup dropped=$dropped es_docs=$docs (burst=20)"
    if python3 -c "
import sys
after_dedup, dropped, docs = float('$after_dedup'), float('$dropped'), int('$docs')
sys.exit(0 if (after_dedup == 1 and dropped == 19 and docs == 1) else 1)"; then
        record_result TS-020 PASS "$detail"
    else
        record_result TS-020 FAIL "$detail"
    fi
}

# ─── Main ────────────────────────────────────────────────────────────────────

echo "=== Event-loop capability suite (no-GPU sim harness) ==="
# Must precede ensure_stack: the simulators are launched with whatever python3
# is on PATH, and the system interpreter typically lacks Flask.
# A clean clone has no venv. Accept one from any of the usual places, or an
# explicit AB_VENV, and say so plainly rather than silently running the system
# interpreter - which lacks Flask and takes the simulators down on import.
for _venv in "${AB_VENV:-}" "$REPO_ROOT/venv" "$REPO_ROOT/.venv"; do
    if [ -n "$_venv" ] && [ -x "$_venv/bin/python3" ]; then
        export PATH="$_venv/bin:$PATH"
        break
    fi
done
if ! python3 -c "import flask, yaml, confluent_kafka" 2>/dev/null; then
    echo "python3 on PATH is missing test dependencies (flask, pyyaml, confluent-kafka)."
    echo "Create a venv from services/alert/requirements.txt and re-run, or point AB_VENV at one."
    exit 2
fi

if [ "$SKIP_SETUP" -eq 0 ]; then
    ensure_stack
fi

for ts in ts_001 ts_002 ts_003 ts_004 ts_005 ts_006 ts_011 ts_014 ts_020; do
    ts_id="TS-${ts#ts_}"
    if [ -n "$ONLY_TEST" ] && [ "$ONLY_TEST" != "$ts_id" ]; then
        continue
    fi
    $ts
done

stop_ab
start_nim_stub 0

echo ""
echo "=== Capability results ==="
for r in "${RESULTS[@]}"; do echo "  $r"; done
echo "  Passed: $PASS_COUNT  Failed: $FAIL_COUNT"
[ "$FAIL_COUNT" -eq 0 ]
