services:
  alert-bridge:
    build:
      context: ${VSS_APPS_DIR}/services/alert
      dockerfile: Dockerfile.local
    image: vss-alert-bridge:local
    environment:
      VLM_WARMUP_ENABLED: ${VLM_WARMUP_ENABLED:-true}
      FASTAPI_PORT: ${FASTAPI_PORT:-9080}
      ALERT_VLM_ENHANCED_SINK_TYPE: ${ALERT_VLM_ENHANCED_SINK_TYPE:-}
      ALERT_VLM_INCIDENT_TOPIC: ${ALERT_VLM_INCIDENT_TOPIC:-mdx-vlm-incidents}
      ALERT_VLM_ALERT_TOPIC: ${ALERT_VLM_ALERT_TOPIC:-mdx-vlm-alerts}
