# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BaseConfig:
  minDetectorConfidence: 0.266
  checkClassMatch: 1
  useBatchNumForFrameId: 1

TargetManagement:
  enableBboxUnClipping: 1
  preserveStreamUpdateOrder: 0
  maxTargetsPerStream: 200
  minIouDiff4NewTarget: 0.3
  minTrackerConfidence: 0.6
  probationAge: 17
  maxShadowTrackingAge: 150
  earlyTerminationAge: 7
  maxTrajectoryBufferLength: -1

TrajectoryManagement:
  useUniqueID: 0
  enableReAssoc: 1
  minMatchingScore4Overall: 0.95
  minTrackletMatchingScore: 0.3
  minMatchingScore4ReidSimilarity: 0
  matchingScoreWeight4TrackletSimilarity: 0.8
  matchingScoreWeight4ReidSimilarity: 0
  minTrajectoryLength4Projection: 34
  prepLength4TrajectoryProjection: 58
  trajectoryProjectionLength: 33
  maxAngle4TrackletMatching: 67
  minSpeedSimilarity4TrackletMatching: 0.06
  minBboxSizeSimilarity4TrackletMatching: 0.1
  maxTrackletMatchingTimeSearchRange: 27
  trajectoryProjectionProcessNoiseScale: 0.01
  trajectoryProjectionMeasurementNoiseScale: 100
  trackletSpacialSearchRegionScale: 0.01
  reidExtractionInterval: 0

DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  minMatchingScore4Overall: 0.5
  minMatchingScore4SizeSimilarity: 0.1
  minMatchingScore4Iou: 0.25
  matchingScoreWeight4SizeSimilarity: 0.2
  matchingScoreWeight4Iou: 0.6
  tentativeDetectorConfidence: 0.8
  minMatchingScore4TentativeIou: 0.25
  minMatchingScore4PeerAssocIou: 0.25

StateEstimator:
  stateEstimatorType: 4
  processNoiseVar4Loc: 56.3
  processNoiseVar4Size: 96.1
  processNoiseVar4Vel: 84.6
  measurementNoiseVar4Detector: 78.4
  measurementNoiseVar4Tracker: 82.3

PoseEstimator:
  poseEstimatorType: 1
  useVPICropScaler: 1
  operateOnClassIds: [0]
  batchSize: 1
  workspaceSize: 1000
  inferDims: [3, 256, 192]
  networkMode: 1
  inputOrder: 0
  colorFormat: 0
  offsets: [123.6750, 116.2800, 103.5300]
  netScaleFactor: 0.00392156
  onnxFile: /opt/storage/BodyPose3DNet/bodypose3dnet_accuracy.onnx
  modelEngineFile: /opt/storage/BodyPose3DNet/bodypose3dnet_accuracy.onnx_b1_gpu0_fp16.engine
  poseInferenceInterval: -1

ObjectModelProjection:
  outputFootLocation: 1
  minPoseConfidence: 0.95
  cameraModelFilepath:
    Camera: /tmp/camInfo/Camera.yml
    Camera_01: /tmp/camInfo/Camera_01.yml
    Camera_02: /tmp/camInfo/Camera_02.yml
    Camera_03: /tmp/camInfo/Camera_03.yml
  objectModelType: 0

MultiViewAssociator:
  multiViewAssociatorType: 1
  enableLatePeerReAssoc: 1
  enableIDCorrection: 0
  enableSeeThrough: 1
  maxPeerTrackletSize: 30
  recentlyActiveAge: 150
  minCommonFrames4MatchScore: 15
  minPeerTrackletMatchScore: 0.25
  minPeerVisibility4Fusion: 0.1
  maxPeerToPredDistance4Fusion: 2.0
  maxTrackletMatchingTimeSearchRange: 5
  maxPeerFrameDiff4NoDet: 5

Communicator:
  communicatorType: 2
  pubSubInfoConfigPath: /tmp/generated/pub_sub_info_config.yml
  mqttProtoAdaptorConfigPath: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/metropolis_perception_app/configs/config_mqtt.txt
