# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

llmNameSlug: nemotron-3-nano

global:
  llmName: "nvidia/nemotron-3-nano"
  vlmName: "nim_nvidia_cosmos3-nano-reasoner_modelopt-fp8-final_format_fix"

vlmName: "nim_nvidia_cosmos3-nano-reasoner_modelopt-fp8-final_format_fix"

vlmPrecision:
  byGpuType:
    H100: fp8
    L40S: fp8
    RTXPRO6000BW: nvfp4
  fp8:
    vlmName: "nim_nvidia_cosmos3-nano-reasoner_modelopt-fp8-final_format_fix"
    modelPath: "ngc:nim/nvidia/cosmos3-nano-reasoner:modelopt-fp8-final_format_fix"
  nvfp4:
    vlmName: "nim_nvidia_cosmos3-nano-reasoner_modelopt-nvfp4-full-quantize-final_format_fix"
    modelPath: "ngc:nim/nvidia/cosmos3-nano-reasoner:modelopt-nvfp4-full-quantize-final_format_fix"

vss-summarization:
  llmService: "nemotron-3-nano"
  vlmService: "vss-rtvi-vlm"

agent:
  vss-agent:
    llmServiceName: "nemotron-3-nano"

rtvi:
  vss-rtvi-vlm:
    enabled: true
    useSharedNim: false
    modelPath: "ngc:nim/nvidia/cosmos3-nano-reasoner:modelopt-fp8-final_format_fix"

nims:
  enabled: true
  gpuType: H100
  nemotron:
    enabled: false
  nemotron35:
    enabled: false
  nemotron3:
    enabled: true
    modelPrecision: "fp8"
